@echo off
echo Verifying ORBT/STAMPED compliance setup...
echo.
echo Checking if metadata table exists...
"C:\Program Files\PostgreSQL\17\bin\psql.exe" "postgresql://Marketing%%20DB_owner:npg_OsE4Z2oPCpiT@ep-ancient-waterfall-a42vy0du-pooler.us-east-1.aws.neon.tech/Marketing%%20DB?sslmode=require&channel_binding=require" -c "SELECT COUNT(*) as metadata_count FROM marketing.marketing_company_column_metadata;"
echo.
echo Checking table structure...
"C:\Program Files\PostgreSQL\17\bin\psql.exe" "postgresql://Marketing%%20DB_owner:npg_OsE4Z2oPCpiT@ep-ancient-waterfall-a42vy0du-pooler.us-east-1.aws.neon.tech/Marketing%%20DB?sslmode=require&channel_binding=require" -c "\d marketing.marketing_company_column_metadata"
echo.
echo Sample metadata entries...
"C:\Program Files\PostgreSQL\17\bin\psql.exe" "postgresql://Marketing%%20DB_owner:npg_OsE4Z2oPCpiT@ep-ancient-waterfall-a42vy0du-pooler.us-east-1.aws.neon.tech/Marketing%%20DB?sslmode=require&channel_binding=require" -c "SELECT column_name, column_number, column_format FROM marketing.marketing_company_column_metadata ORDER BY column_number LIMIT 10;"
pause 